class_name TFProjectSettings
extends RefCounted

## Project-level metadata and data provenance.
##
## V1 terrain is NOT georeferenced. The coordinate system is an explicit local
## engineering grid and the vertical datum is an assumed elevation. These
## fields exist so that a real CRS and a real datum can be recorded later
## without changing the model, and so nothing in the app can quietly imply the
## data is survey grade.

const STATUS_PROPOSED := "proposed"
const STATUS_SIMULATED := "simulated"
const STATUS_FIELD_MEASURED := "field_measured"
const STATUS_CERTIFIED := "professionally_certified"

const STATUS_LABELS := {
	"proposed": "Proposed",
	"simulated": "Simulated",
	"field_measured": "Field measured",
	"professionally_certified": "Professionally certified",
}

const DISCLAIMER := "Concept simulation - not for construction"
const LONG_DISCLAIMER := "TerraForge produces proposed and simulated information only. Nothing in this project has been surveyed, staked in the field, inspected, tested, reviewed, sealed, permitted or approved. Slope stability, drainage, soil bearing capacity, settlement, groundwater, property boundaries and permitting all require investigation by qualified licensed professionals."

var project_name: String = "Untitled site"
var author: String = ""
var units: TFUnitSystem = TFUnitSystem.new("m", "m3")

# Site grid (the canonical terrain definition)
var site_cols: int = 121
var site_rows: int = 121
var site_spacing_m: float = 2.0
var site_origin: Vector2 = Vector2(-120.0, -120.0)

# Provenance / reference frame
var coordinate_system_label: String = "TerraForge local grid (project origin 0,0)"
var horizontal_datum: String = "Not georeferenced - local assumed"
var vertical_datum: String = "Not surveyed - local assumed datum"
var assumed_elevation_m: float = 0.0
var existing_surface_source: String = "Synthetic flat surface generated by TerraForge (no survey data)"
var data_status: String = STATUS_SIMULATED

var created_unix: int = 0
var modified_unix: int = 0
var notes: String = ""


func _init() -> void:
	created_unix = int(Time.get_unix_time_from_system())
	modified_unix = created_unix


func touch() -> void:
	modified_unix = int(Time.get_unix_time_from_system())


func site_extent_m() -> Vector2:
	return Vector2(float(site_cols - 1) * site_spacing_m, float(site_rows - 1) * site_spacing_m)


func site_area_m2() -> float:
	var e := site_extent_m()
	return e.x * e.y


func status_label() -> String:
	return String(STATUS_LABELS.get(data_status, data_status))


static func format_time(unix: int) -> String:
	if unix <= 0:
		return "-"
	return Time.get_datetime_string_from_unix_time(unix, true) + " UTC"


func to_dict() -> Dictionary:
	return {
		"project_name": project_name,
		"author": author,
		"units": units.to_dict(),
		"site": {
			"cols": site_cols, "rows": site_rows,
			"spacing_m": site_spacing_m,
			"origin": [site_origin.x, site_origin.y],
			"extent_m": [site_extent_m().x, site_extent_m().y],
		},
		"provenance": {
			"coordinate_system_label": coordinate_system_label,
			"horizontal_datum": horizontal_datum,
			"vertical_datum": vertical_datum,
			"assumed_elevation_m": assumed_elevation_m,
			"existing_surface_source": existing_surface_source,
			"data_status": data_status,
			"disclaimer": DISCLAIMER,
			"long_disclaimer": LONG_DISCLAIMER,
		},
		"created_unix": created_unix,
		"modified_unix": modified_unix,
		"notes": notes,
	}


static func from_dict(d: Dictionary) -> TFProjectSettings:
	var s := TFProjectSettings.new()
	s.project_name = String(d.get("project_name", "Untitled site"))
	s.author = String(d.get("author", ""))
	s.units = TFUnitSystem.from_dict(d.get("units", {}))
	var site: Dictionary = d.get("site", {})
	s.site_cols = int(site.get("cols", 121))
	s.site_rows = int(site.get("rows", 121))
	s.site_spacing_m = float(site.get("spacing_m", 2.0))
	var o: Array = site.get("origin", [-120.0, -120.0])
	if o.size() >= 2:
		s.site_origin = Vector2(float(o[0]), float(o[1]))
	var pv: Dictionary = d.get("provenance", {})
	s.coordinate_system_label = String(pv.get("coordinate_system_label", s.coordinate_system_label))
	s.horizontal_datum = String(pv.get("horizontal_datum", s.horizontal_datum))
	s.vertical_datum = String(pv.get("vertical_datum", s.vertical_datum))
	s.assumed_elevation_m = float(pv.get("assumed_elevation_m", 0.0))
	s.existing_surface_source = String(pv.get("existing_surface_source", s.existing_surface_source))
	s.data_status = String(pv.get("data_status", STATUS_SIMULATED))
	# V1 can only ever produce proposed or simulated data. Refuse to load a
	# higher claim from a file - it cannot have been earned inside this app.
	if s.data_status != STATUS_PROPOSED and s.data_status != STATUS_SIMULATED:
		push_warning("TerraForge: refusing imported data_status '%s'; forcing 'simulated'." % s.data_status)
		s.data_status = STATUS_SIMULATED
	s.created_unix = int(d.get("created_unix", Time.get_unix_time_from_system()))
	s.modified_unix = int(d.get("modified_unix", s.created_unix))
	s.notes = String(d.get("notes", ""))
	return s
